FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o agent ./cmd/agent

FROM alpine:latest

# Install docker cli
RUN apk add --no-cache docker-cli

COPY --from=builder /app/agent /bin/agent

CMD ["/bin/agent"]
